version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  org-app:
    build:
      context: ./organization
      dockerfile: Dockerfile
    container_name: org-app
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    links:
      - mongodb:org-db

  valid-app:
    build:
      context: ./valid
      dockerfile: Dockerfile
    container_name: valid-app
    depends_on:
      - rabbitmq
    ports:
      - "4000:8000"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
