version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  db-app:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: db-app
    ports:
      - "8081:8081"
    networks:
      - app-network
    links:
      - mongodb:org-db

  org-app:
    build:
      context: ./organization
      dockerfile: Dockerfile
    container_name: org-app
    ports:
      - "8082:8082"
    networks:
      - app-network
    links:
      - mongodb:org-db

  valid-app:
    build:
      context: ./valid
      dockerfile: Dockerfile
    container_name: valid-app
    ports:
      - "4000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
