package com.data.database.model;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "answer")
public class Answer {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String a_id;
    @DynamoDBAttribute
    private String q_id;
    @DynamoDBAttribute
    private String answer;
    @DynamoDBAttribute
    @DynamoDBIndexHashKey
    private String f_id;
}
