package com.data.database.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "form")
public class Form {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String fId;
    @DynamoDBAttribute
    private String link;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String orgId;

    // other fields can be added as needed

}
