package com.data.database.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "question")
public class Question {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String q_id;
    @DynamoDBAttribute
    private String question;
    @DynamoDBAttribute
    private String type;
    @DynamoDBAttribute
    @DynamoDBIndexHashKey
    private String f_id;

}
