package com.data.organization.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "org_user")
public class OrgUser {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute
    private String name;
    @JsonIgnore
    @DynamoDBAttribute
    private String password;
    @JsonIgnore
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String address;
    @DynamoDBAttribute
    private String country;
    @DynamoDBAttribute
    private Set<Role> roles = new HashSet<>();
    @JsonIgnore
    @DynamoDBAttribute
    private Boolean locked;
    @JsonIgnore
    @DynamoDBAttribute
    private Boolean enabled;

}
